// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package app

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetValueGetValueValueOutput includes the requested fields of the GraphQL type ValueOutput.
type GetValueGetValueValueOutput struct {
	Value string `json:"value"`
}

// GetValue returns GetValueGetValueValueOutput.Value, and is useful for accessing the field via an interface.
func (v *GetValueGetValueValueOutput) GetValue() string { return v.Value }

// GetValueResponse is returned by GetValue on success.
type GetValueResponse struct {
	GetValue GetValueGetValueValueOutput `json:"getValue"`
}

// GetGetValue returns GetValueResponse.GetValue, and is useful for accessing the field via an interface.
func (v *GetValueResponse) GetGetValue() GetValueGetValueValueOutput { return v.GetValue }

// SetValueResponse is returned by SetValue on success.
type SetValueResponse struct {
	SetValue SetValueSetValueValueOutput `json:"setValue"`
}

// GetSetValue returns SetValueResponse.SetValue, and is useful for accessing the field via an interface.
func (v *SetValueResponse) GetSetValue() SetValueSetValueValueOutput { return v.SetValue }

// SetValueSetValueValueOutput includes the requested fields of the GraphQL type ValueOutput.
type SetValueSetValueValueOutput struct {
	Value string `json:"value"`
}

// GetValue returns SetValueSetValueValueOutput.Value, and is useful for accessing the field via an interface.
func (v *SetValueSetValueValueOutput) GetValue() string { return v.Value }

type ValueInput struct {
	Value string `json:"value"`
}

// GetValue returns ValueInput.Value, and is useful for accessing the field via an interface.
func (v *ValueInput) GetValue() string { return v.Value }

// __SetValueInput is used internally by genqlient
type __SetValueInput struct {
	Value ValueInput `json:"value"`
}

// GetValue returns __SetValueInput.Value, and is useful for accessing the field via an interface.
func (v *__SetValueInput) GetValue() ValueInput { return v.Value }

// The query or mutation executed by GetValue.
const GetValue_Operation = `
query GetValue {
	getValue {
		value
	}
}
`

func GetValue(
	ctx_ context.Context,
	client_ graphql.Client,
) (*GetValueResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetValue",
		Query:  GetValue_Operation,
	}
	var err_ error

	var data_ GetValueResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by SetValue.
const SetValue_Operation = `
mutation SetValue ($value: ValueInput!) {
	setValue(input: $value) {
		value
	}
}
`

func SetValue(
	ctx_ context.Context,
	client_ graphql.Client,
	value ValueInput,
) (*SetValueResponse, error) {
	req_ := &graphql.Request{
		OpName: "SetValue",
		Query:  SetValue_Operation,
		Variables: &__SetValueInput{
			Value: value,
		},
	}
	var err_ error

	var data_ SetValueResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
