apiVersion: v2
appVersion: 1.0.0
version: v1.1.0
description: example
name: example-app
maintainers:
  - email: wael.jammal@azarc.io
    name: Wael Jammal
sources:
  - https://github.com/azarc-io/verathread-app-temp
