package pubresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"github.com/azarc-io/example-app/internal/gql/graph/common/model"
	pubgraph "github.com/azarc-io/example-app/internal/gql/graph/public"
)

// SetValue is the resolver for the setValue field.
func (r *mutationResolver) SetValue(ctx context.Context, input model.ValueInput) (*model.ValueOutput, error) {
	return r.AppService.GQLSetValue(ctx, input)
}

// Mutation returns pubgraph.MutationResolver implementation.
func (r *Resolver) Mutation() pubgraph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
