package pvtresolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"github.com/azarc-io/verathread-app-template/internal/gql/graph/common/model"
	pvtgraph "github.com/azarc-io/verathread-app-template/internal/gql/graph/private"
)

// SetValueInternal is the resolver for the setValueInternal field.
func (r *mutationResolver) SetValueInternal(ctx context.Context, input model.ValueInput) (*model.ValueOutput, error) {
	return r.AppService.GQLSetValue(ctx, input)
}

// SetValue is the resolver for the setValue field.
func (r *mutationResolver) SetValue(ctx context.Context, input model.ValueInput) (*model.ValueOutput, error) {
	return r.AppService.GQLSetValue(ctx, input)
}

// Mutation returns pvtgraph.MutationResolver implementation.
func (r *Resolver) Mutation() pvtgraph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
