FROM --platform=$BUILDPLATFORM alpine:3.20
LABEL authors="waeljammal"

ARG TARGETOS
ARG TARGETARCH

COPY bin/${TARGETOS}-${TARGETARCH}/example-app /
RUN chmod +x /example-app
ENTRYPOINT ["/example-app"]
